[package]
name = "toggle_fullscreen"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bspc_rust_lib = { path = "/home/benkenobi/Documents/coding/bspc_rust_lib" }
